# Generated by Django 4.0 on 2023-08-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeproducts',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
