# Generated by Django 4.0 on 2023-08-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_rename_quanity_coffeeproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeproducts',
            name='image',
        ),
    ]
