# Generated by Django 4.0 on 2023-08-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=True)),
                ('warehoused_products', models.ManyToManyField(to='Farmer.CoffeeProducts')),
                ('warehouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.warehouser')),
            ],
        ),
    ]
