# Generated by Django 4.0 on 2023-11-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farming', '0017_farmerprofile_altitude_and_more'),
        ('Authentication', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10)),
                ('warehouser', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('shipping_approval', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('warehouse_area_storage', models.IntegerField(default=0)),
                ('processed_products', models.ManyToManyField(to='Farming.ProcessedProducts')),
                ('warehoused_products', models.ManyToManyField(to='Warehouser.ShippingManifest')),
                ('warehouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts')),
            ],
        ),
    ]
