# Generated by Django 4.0 on 2023-10-02 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0007_coffeeproducts_shipment_successful'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.buyer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.processedproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('processed_products', models.ManyToManyField(to='Farming.ProcessedProducts')),
                ('product_orders', models.ManyToManyField(to='Warehouser.ProductOrder')),
                ('warehoused_products', models.ManyToManyField(to='Farming.CoffeeProducts')),
                ('warehouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.warehouser')),
            ],
        ),
    ]
