# Generated by Django 4.0 on 2023-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
