# Generated by Django 4.0 on 2023-11-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanifest',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
