# Generated by Django 4.0 on 2023-10-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouser', '0003_remove_warehouse_product_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
