# Generated by Django 4.0 on 2023-12-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0021_account_phone_number'),
        ('Warehouser', '0004_alter_warehouse_warehouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
