# Generated by Django 4.0 on 2023-10-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0007_coffeeproducts_shipment_successful'),
        ('Warehouser', '0004_delete_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('approved', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts')),
                ('warehouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.warehouser')),
            ],
        ),
    ]
