# Generated by Django 4.0 on 2023-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouser', '0006_rename_approved_shippingmanifest_shipping_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmanifest',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
