# Generated by Django 4.0 on 2023-10-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0007_coffeeproducts_shipment_successful'),
        ('Warehouser', '0007_shippingmanifest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanifest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts'),
        ),
    ]
