# Generated by Django 4.0 on 2023-10-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0007_coffeeproducts_shipment_successful'),
        ('Warehouser', '0008_alter_shippingmanifest_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmanifest',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts'),
        ),
        migrations.AlterField(
            model_name='shippingmanifest',
            name='warehouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.warehouser'),
        ),
    ]
