# Generated by Django 4.0 on 2024-02-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Warehouser', '0005_alter_warehouse_warehouser'),
        ('Authentication', '0021_account_phone_number'),
        ('Orders', '0013_alter_cart_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account')),
                ('product', models.ManyToManyField(to='Orders.CartItem')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Warehouser.warehouse')),
            ],
        ),
    ]
