# Generated by Django 4.0 on 2024-02-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_cart_buyer'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
    ]
