# Generated by Django 4.0 on 2023-08-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('warehouse_approved', models.BooleanField(default=False)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.farmer')),
                ('products', models.ManyToManyField(to='Farming.CoffeeProducts')),
            ],
        ),
    ]
