# Generated by Django 4.0 on 2023-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='acidity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='caffeine',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='cup_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='cup_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='cupped_by',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='drying',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='grade',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='lot_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='origin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coffeeproducts',
            name='processing',
            field=models.TextField(default=''),
        ),
    ]
