# Generated by Django 4.0 on 2023-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0002_coffeeproducts_acidity_coffeeproducts_caffeine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='requested_warehousing',
            field=models.BooleanField(default=False),
        ),
    ]
