# Generated by Django 4.0 on 2023-09-25 11:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_profile_profile_pic'),
        ('Farming', '0004_alter_coffeeproducts_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlzyg12i7/image/upload/v1695058480/user_dy7js1.jpg', max_length=255, verbose_name='products')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts')),
                ('rating', models.ManyToManyField(to='Farming.Ratings')),
            ],
        ),
    ]
