# Generated by Django 4.0 on 2023-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0005_ratings_processedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedproducts',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedproducts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
