# Generated by Django 4.0 on 2023-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0007_coffeeproducts_shipment_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproducts',
            name='producer',
            field=models.TextField(default=''),
        ),
    ]
