# Generated by Django 4.0 on 2023-10-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0008_alter_coffeeproducts_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='producer_email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coffeeproducts',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
