# Generated by Django 4.0 on 2023-10-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0009_coffeeproducts_producer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeproducts',
            old_name='producer_email',
            new_name='email',
        ),
    ]
