# Generated by Django 4.0 on 2023-10-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0011_remove_coffeeproducts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='farmer_email',
            field=models.TextField(default=''),
        ),
    ]
