# Generated by Django 4.0 on 2023-10-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0013_remove_coffeeproducts_farmer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
