# Generated by Django 4.0 on 2023-10-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0014_coffeeproducts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproducts',
            name='producer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
