# Generated by Django 4.0 on 2023-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0015_alter_coffeeproducts_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='products',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
