# Generated by Django 4.0 on 2023-10-30 11:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0016_remove_farmerprofile_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='altitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='annual_rainfall_amount',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='availability',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='certification_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='coffee_variety',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='county',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='factory_chairman',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='factory_manager',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='harvest_season',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='no_of_farmers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='no_of_trees',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='society_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='total_acreage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='wet_mill_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processedproducts',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='products'),
        ),
    ]
