# Generated by Django 4.0 on 2023-11-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_alter_profile_profile_pic'),
        ('Farming', '0017_farmerprofile_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
