# Generated by Django 4.0 on 2023-11-26 17:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_account_notifications'),
        ('Farming', '0018_alter_farmerprofile_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='cupping_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farming_method',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='grower_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='men',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='processing_method',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='soil_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='women',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts'),
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', cloudinary.models.CloudinaryField(max_length=255, verbose_name='/stories')),
                ('caption', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account')),
            ],
        ),
    ]
