# Generated by Django 4.0 on 2023-11-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0019_farmerprofile_country_farmerprofile_cupping_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedproducts',
            name='code',
            field=models.BigIntegerField(null=True),
        ),
    ]
