# Generated by Django 4.0 on 2023-12-01 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0021_alter_processedproducts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 0)),
        ),
    ]
