# Generated by Django 4.0 on 2023-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0022_stories_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='estate_name',
            field=models.TextField(default=''),
        ),
    ]
