# Generated by Django 4.0 on 2024-02-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0023_farmerprofile_estate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproducts',
            name='species',
            field=models.TextField(default=''),
        ),
    ]
