# Generated by Django 4.0 on 2023-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depending_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='email')),
            ],
        ),
    ]
