# Generated by Django 4.0 on 2023-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depending_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depending_account',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
