# Generated by Django 4.0 on 2023-09-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depending_Accounts', '0002_depending_account_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depending_Account',
            new_name='Pending_Account',
        ),
    ]
