# Generated by Django 4.0 on 2023-09-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depending_Accounts', '0003_rename_depending_account_pending_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_account',
            name='account_validated',
            field=models.BooleanField(default=True),
        ),
    ]
