# Generated by Django 4.0 on 2023-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depending_Accounts', '0004_pending_account_account_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_account',
            name='index',
            field=models.CharField(default='', max_length=10),
        ),
    ]
