# Generated by Django 4.0 on 2023-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depending_Accounts', '0005_pending_account_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_account',
            name='account_validated',
        ),
        migrations.RemoveField(
            model_name='pending_account',
            name='password',
        ),
        migrations.AddField(
            model_name='pending_account',
            name='farmer_registration_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending_account',
            name='phone_number',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
