# Generated by Django 4.0 on 2023-09-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_farmer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_warehouser',
        ),
    ]
