# Generated by Django 4.0 on 2023-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_account_is_buyer_remove_account_is_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='index',
            field=models.CharField(default='', max_length=10),
        ),
    ]
