# Generated by Django 4.0 on 2023-09-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginWarehouser',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentication.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('Authentication.account',),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FARMER', 'Farmer'), ('ORIGINWAREHOUSER', 'OriginWarehouser'), ('WAREHOUSER', 'Warehouser'), ('BUYER', 'Buyer')], default='BUYER', max_length=100, verbose_name='Type'),
        ),
    ]
