# Generated by Django 4.0 on 2023-10-30 11:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='http://res.cloudinary.com/dlzyg12i7/image/upload/v1695058480/user_dy7js1.jpg', max_length=255, verbose_name='images'),
        ),
    ]
