# Generated by Django 4.0 on 2023-12-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_account_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
