# Generated by Django 4.0 on 2023-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_account_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
