# Generated by Django 4.0 on 2023-11-07 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farming', '0017_farmerprofile_altitude_and_more'),
        ('Authentication', '0014_alter_profile_profile_pic'),
        ('Warehouser', '0002_alter_shippingmanifest_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('country', models.TextField(default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('marker', models.IntegerField(default=0)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.buyer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.coffeeproducts')),
                ('warehouse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Warehouser.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default=0)),
                ('grind', models.TextField(default='', null=True)),
                ('roast_type', models.TextField(default='', null=True)),
                ('type', models.TextField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farming.processedproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account')),
                ('products', models.ManyToManyField(to='Orders.CartItem')),
            ],
        ),
    ]
