# Generated by Django 4.0 on 2023-11-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0020_processedproducts_code'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='green_product',
            field=models.ManyToManyField(to='Farming.CoffeeProducts'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_product',
            field=models.ManyToManyField(to='Farming.ProcessedProducts'),
        ),
    ]
