# Generated by Django 4.0 on 2023-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouser', '__first__'),
        ('Authentication', '0001_initial'),
        ('Farming', '0002_coffeeproducts_acidity_coffeeproducts_caffeine_and_more'),
        ('Orders', '0003_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
