# Generated by Django 4.0 on 2023-11-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='code',
            field=models.BigIntegerField(null=True),
        ),
    ]
