# Generated by Django 4.0 on 2023-09-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_rename_requests_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='is_accepted',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_warehoused',
        ),
    ]
