# Generated by Django 4.0 on 2023-11-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0021_alter_processedproducts_code'),
        ('Orders', '0006_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Farming.processedproducts'),
        ),
    ]
