# Generated by Django 4.0 on 2023-10-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Orders', '0006_delete_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
