# Generated by Django 4.0 on 2023-10-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_originwarehouser_alter_account_type'),
        ('Farming', '0007_coffeeproducts_shipment_successful'),
        ('Orders', '0008_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.buyer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='Farming.CoffeeProducts'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.buyer'),
        ),
    ]
