# Generated by Django 4.0 on 2023-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='green_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processed_product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='Orders.CartItem'),
        ),
    ]
