# Generated by Django 4.0 on 2024-01-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
