# Generated by Django 4.0 on 2024-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_cart_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
