# Generated by Django 4.0 on 2024-02-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0015_alter_cartitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
