# Generated by Django 4.0 on 2024-02-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0024_coffeeproducts_species'),
        ('Orders', '0016_cartitem_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(default='', max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.FloatField(default=0)),
                ('grind', models.TextField(default='', null=True)),
                ('roast_type', models.TextField(default='', null=True)),
                ('type', models.TextField(default='')),
                ('subscription', models.BooleanField(default=False)),
                ('code', models.CharField(default='', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farming.processedproducts')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='wishlist',
            field=models.ManyToManyField(to='Orders.WishListItem'),
        ),
    ]
