# Generated by Django 4.0 on 2024-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming', '0024_coffeeproducts_species'),
        ('Orders', '0017_wishlistitem_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='wishlist',
            field=models.ManyToManyField(to='Farming.ProcessedProducts'),
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
