# Generated by Django 4.0 on 2023-10-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
