# Generated by Django 4.0 on 2023-11-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_recipient_remove_notification_recepient_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
