# Generated by Django 4.0 on 2023-12-01 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0006_remove_notification_recipients_delete_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 12, 0)),
        ),
    ]
