# Generated by Django 4.0 on 2024-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0007_notification_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='route',
            field=models.TextField(blank=True),
        ),
    ]
